// Auto-generated file - do not edit

export enum DevicesIcon {
    device = 'devices.svg#device',
    air_filter = 'devices.svg#air_filter',
    bearing = 'devices.svg#bearing',
    breaker = 'devices.svg#breaker',
    camera = 'devices.svg#camera',
    capacitor_large = 'devices.svg#capacitor_large',
    capacitor_symbol = 'devices.svg#capacitor_symbol',
    computer = 'devices.svg#computer',
    contactor = 'devices.svg#contactor',
    diode = 'devices.svg#diode',
    ephesus_fixture = 'devices.svg#ephesus_fixture',
    ephesus_gateway = 'devices.svg#ephesus_gateway',
    fan = 'devices.svg#fan',
    generator = 'devices.svg#generator',
    generator_off = 'devices.svg#generator_off',
    radio_handheld = 'devices.svg#radio_handheld',
    network_switch = 'devices.svg#network_switch',
    pdu = 'devices.svg#pdu',
    pump = 'devices.svg#pump',
    server = 'devices.svg#server',
    servers = 'devices.svg#servers',
    ssol = 'devices.svg#ssol',
    switch = 'devices.svg#switch',
    switchgear = 'devices.svg#switchgear',
    transformer = 'devices.svg#transformer',
    utility = 'devices.svg#utility',
    vfd = 'devices.svg#vfd',
    xstorage = 'devices.svg#xstorage',
    xstorage_alt = 'devices.svg#xstorage_alt',
    battery_large_reset = 'devices.svg#battery_large_reset',
    battery_large_reset_outline = 'devices.svg#battery_large_reset_outline',
    battery_large_showing_terminals = 'devices.svg#battery_large_showing_terminals',
    battery_large = 'devices.svg#battery_large',
    battery_large_outline = 'devices.svg#battery_large_outline',
    ats_alt = 'devices.svg#ats_alt',
    ats = 'devices.svg#ats',
    distribution_box = 'devices.svg#distribution_box',
    distribution_box_outline = 'devices.svg#distribution_box_outline',
    drive = 'devices.svg#drive',
    meter_face = 'devices.svg#meter_face',
    motor_alt = 'devices.svg#motor_alt',
    motor_controller_outline = 'devices.svg#motor_controller_outline',
    motor_controller = 'devices.svg#motor_controller',
    motor_outline = 'devices.svg#motor_outline',
    motor_starter = 'devices.svg#motor_starter',
    motor = 'devices.svg#motor',
    relay = 'devices.svg#relay',
    sensor_alt = 'devices.svg#sensor_alt',
    sensor_device_alt = 'devices.svg#sensor_device_alt',
    sensor_device = 'devices.svg#sensor_device',
    sensor = 'devices.svg#sensor',
    device_info = 'devices.svg#device_info',
    trip_curve_alt = 'devices.svg#trip_curve_alt',
    trip_curve = 'devices.svg#trip_curve',
    trip_unit = 'devices.svg#trip_unit',
    ups_outline = 'devices.svg#ups_outline',
    ups = 'devices.svg#ups',
    fan_circled = 'devices.svg#fan_circled',
    air_conditioner = 'devices.svg#air_conditioner',
    smoke_detector = 'devices.svg#smoke_detector',
    rfid = 'devices.svg#rfid',
    utility_disabled = 'devices.svg#utility_disabled',
    breaker_closed = 'devices.svg#breaker_closed',
    battery_disabled = 'devices.svg#battery_disabled',
    battery_disabled_alt = 'devices.svg#battery_disabled_alt',
    ethernet_port = 'devices.svg#ethernet_port',
    wind_turbine = 'devices.svg#wind_turbine',
}

export enum DeviceIcon {
    battery = 'device.svg#battery',
}

export enum SportsIcon {
    ephesus_fixture = 'sports.svg#ephesus_fixture',
    ephesus_gateway = 'sports.svg#ephesus_gateway',
    baseball = 'sports.svg#baseball',
    basketball_hoop = 'sports.svg#basketball_hoop',
    boxing_glove = 'sports.svg#boxing_glove',
    football_helmet = 'sports.svg#football_helmet',
    hockey_puck = 'sports.svg#hockey_puck',
    hockey_sticks = 'sports.svg#hockey_sticks',
    tennis = 'sports.svg#tennis',
}

export enum LightingIcon {
    ephesus_fixture = 'lighting.svg#ephesus_fixture',
    ephesus_gateway = 'lighting.svg#ephesus_gateway',
    dimmer = 'lighting.svg#dimmer',
    light_switch = 'lighting.svg#light_switch',
    outlet = 'lighting.svg#outlet',
    light_bulb = 'lighting.svg#light_bulb',
    ceiling_light = 'lighting.svg#ceiling_light',
}

export enum StatusIcon {
    bypass_battery = 'status.svg#bypass_battery',
    current = 'status.svg#current',
    current_circled = 'status.svg#current_circled',
    current_circled_outline = 'status.svg#current_circled_outline',
    flow = 'status.svg#flow',
    pipe_disconnected = 'status.svg#pipe_disconnected',
    pipe_leak = 'status.svg#pipe_leak',
    pipe = 'status.svg#pipe',
    grade_a = 'status.svg#grade_a',
    grade_b = 'status.svg#grade_b',
    grade_c = 'status.svg#grade_c',
    grade_d = 'status.svg#grade_d',
    grade_f = 'status.svg#grade_f',
    health = 'status.svg#health',
    incident = 'status.svg#incident',
    incident_active = 'status.svg#incident_active',
    incident_resolved = 'status.svg#incident_resolved',
    maintenance = 'status.svg#maintenance',
    environment = 'status.svg#environment',
    moisture = 'status.svg#moisture',
    overlap = 'status.svg#overlap',
    power_circled = 'status.svg#power_circled',
    power_circled_outline = 'status.svg#power_circled_outline',
    priority = 'status.svg#priority',
    push_notification_solid = 'status.svg#push_notification_solid',
    push_notification = 'status.svg#push_notification',
    qrcode = 'status.svg#qrcode',
    scan_qrcode = 'status.svg#scan_qrcode',
    running_high = 'status.svg#running_high',
    running_low = 'status.svg#running_low',
    stopped = 'status.svg#stopped',
    stopping = 'status.svg#stopping',
    support = 'status.svg#support',
    temp = 'status.svg#temp',
    toggle_on = 'status.svg#toggle_on',
    toggle_off = 'status.svg#toggle_off',
    toggle_on_outlined = 'status.svg#toggle_on_outlined',
    toggle_off_outlined = 'status.svg#toggle_off_outlined',
    trending_up = 'status.svg#trending_up',
    trending_down = 'status.svg#trending_down',
    trending_flat = 'status.svg#trending_flat',
    tripped = 'status.svg#tripped',
    vmms = 'status.svg#vmms',
    voltage = 'status.svg#voltage',
    voltage_circled = 'status.svg#voltage_circled',
    voltage_circled_outline = 'status.svg#voltage_circled_outline',
    water = 'status.svg#water',
    water_outline = 'status.svg#water_outline',
    waveform = 'status.svg#waveform',
    leaf = 'status.svg#leaf',
    pressure = 'status.svg#pressure',
    pressure_alt = 'status.svg#pressure_alt',
    apparent_energy = 'status.svg#apparent_energy',
    apparent_power = 'status.svg#apparent_power',
    bypass_alt = 'status.svg#bypass_alt',
    bypass = 'status.svg#bypass',
    flood = 'status.svg#flood',
    frequency = 'status.svg#frequency',
    harmonics = 'status.svg#harmonics',
    phase_angle = 'status.svg#phase_angle',
    power_factor = 'status.svg#power_factor',
    reactive_energy = 'status.svg#reactive_energy',
    reactive_power = 'status.svg#reactive_power',
    real_energy = 'status.svg#real_energy',
    real_power = 'status.svg#real_power',
    sequence = 'status.svg#sequence',
    output_flow = 'status.svg#output_flow',
    input_flow = 'status.svg#input_flow',
    load_factor = 'status.svg#load_factor',
    video_alert_outline = 'status.svg#video_alert_outline',
    power_redundancy = 'status.svg#power_redundancy',
    power_redundancy_off = 'status.svg#power_redundancy_off',
    video_alert = 'status.svg#video_alert',
    video_streaming_outline = 'status.svg#video_streaming_outline',
    video_streaming = 'status.svg#video_streaming',
    incident_maintenance = 'status.svg#incident_maintenance',
    help_desk_log = 'status.svg#help_desk_log',
    notification_log = 'status.svg#notification_log',
    panel_log = 'status.svg#panel_log',
    bolt_off = 'status.svg#bolt_off',
    ppe_level_two_tone = 'status.svg#ppe_level_two_tone',
    blast = 'status.svg#blast',
    left_outline = 'status.svg#left_outline',
    right_outline = 'status.svg#right_outline',
    left = 'status.svg#left',
    right = 'status.svg#right',
    double_triangle = 'status.svg#double_triangle',
    cloud_done = 'status.svg#cloud_done',
    cloud_off_filled = 'status.svg#cloud_off_filled',
    water_energy = 'status.svg#water_energy',
}

export enum ToggleIcon {
    toggle_on = 'toggle.svg#toggle_on',
    toggle_off = 'toggle.svg#toggle_off',
    toggle_on_outlined = 'toggle.svg#toggle_on_outlined',
    toggle_off_outlined = 'toggle.svg#toggle_off_outlined',
}

export enum IndustrialIcon {
    barrel = 'industrial.svg#barrel',
    flask = 'industrial.svg#flask',
    fuel = 'industrial.svg#fuel',
    gas_cylinder = 'industrial.svg#gas_cylinder',
}

export enum AgricultureIcon {
    tree = 'agriculture.svg#tree',
    leaf = 'agriculture.svg#leaf',
    wheat = 'agriculture.svg#wheat',
    soybean = 'agriculture.svg#soybean',
    apple = 'agriculture.svg#apple',
    asparagus = 'agriculture.svg#asparagus',
    corn = 'agriculture.svg#corn',
    barley = 'agriculture.svg#barley',
    barley_alt = 'agriculture.svg#barley_alt',
    grass = 'agriculture.svg#grass',
    tomato = 'agriculture.svg#tomato',
    garlic = 'agriculture.svg#garlic',
    carrot = 'agriculture.svg#carrot',
    potato = 'agriculture.svg#potato',
    broccoli = 'agriculture.svg#broccoli',
    pepper = 'agriculture.svg#pepper',
    chili_pepper = 'agriculture.svg#chili_pepper',
    sunflower = 'agriculture.svg#sunflower',
    silo = 'agriculture.svg#silo',
    tractor = 'agriculture.svg#tractor',
    combine_harvester = 'agriculture.svg#combine_harvester',
    flower = 'agriculture.svg#flower',
    flower_tulip = 'agriculture.svg#flower_tulip',
    hops = 'agriculture.svg#hops',
}

export enum MapsIcon {
    silo = 'maps.svg#silo',
    building = 'maps.svg#building',
    sitemap_outline = 'maps.svg#sitemap_outline',
    warehouse_alt = 'maps.svg#warehouse_alt',
    floor_plan = 'maps.svg#floor_plan',
    garage_closed = 'maps.svg#garage_closed',
}

export enum VehiclesIcon {
    pickup_truck = 'vehicles.svg#pickup_truck',
    forklift = 'vehicles.svg#forklift',
    utility_van = 'vehicles.svg#utility_van',
    car = 'vehicles.svg#car',
    sports_car = 'vehicles.svg#sports_car',
    tractor = 'vehicles.svg#tractor',
    combine_harvester = 'vehicles.svg#combine_harvester',
    ev_plug_domestic_a = 'vehicles.svg#ev_plug_domestic_a',
    ev_plug_domestic_b = 'vehicles.svg#ev_plug_domestic_b',
    ev_plug_domestic_c = 'vehicles.svg#ev_plug_domestic_c',
    ev_plug_domestic_d = 'vehicles.svg#ev_plug_domestic_d',
    ev_plug_domestic_e = 'vehicles.svg#ev_plug_domestic_e',
    ev_plug_domestic_f = 'vehicles.svg#ev_plug_domestic_f',
    ev_plug_domestic_g = 'vehicles.svg#ev_plug_domestic_g',
    ev_plug_domestic_h = 'vehicles.svg#ev_plug_domestic_h',
    ev_plug_domestic_i = 'vehicles.svg#ev_plug_domestic_i',
    ev_plug_domestic_j = 'vehicles.svg#ev_plug_domestic_j',
    ev_plug_domestic_k = 'vehicles.svg#ev_plug_domestic_k',
    ev_plug_domestic_l = 'vehicles.svg#ev_plug_domestic_l',
    ev_plug_iec_60309_2_single_16 = 'vehicles.svg#ev_plug_iec_60309_2_single_16',
    ev_plug_iec_60309_2_three_16 = 'vehicles.svg#ev_plug_iec_60309_2_three_16',
    ev_plug_iec_60309_2_three_32 = 'vehicles.svg#ev_plug_iec_60309_2_three_32',
    ev_plug_iec_60309_2_three_64 = 'vehicles.svg#ev_plug_iec_60309_2_three_64',
    ev_plug_iec_62196_t1 = 'vehicles.svg#ev_plug_iec_62196_t1',
    ev_plug_type_one = 'vehicles.svg#ev_plug_type_one',
    ev_plug_iec_62196_t1_combo = 'vehicles.svg#ev_plug_iec_62196_t1_combo',
    ev_plug_iec_62196_t2 = 'vehicles.svg#ev_plug_iec_62196_t2',
    ev_plug_type_two = 'vehicles.svg#ev_plug_type_two',
    ev_plug_iec_62196_t2_combo = 'vehicles.svg#ev_plug_iec_62196_t2_combo',
    ev_plug_ccs_combo = 'vehicles.svg#ev_plug_ccs_combo',
    ev_plug_iec_62196_t3a = 'vehicles.svg#ev_plug_iec_62196_t3a',
    ev_plug_iec_62196_t3c = 'vehicles.svg#ev_plug_iec_62196_t3c',
    ev_plug_tesla_r = 'vehicles.svg#ev_plug_tesla_r',
    ev_plug_tesla_s = 'vehicles.svg#ev_plug_tesla_s',
    ev_plug_chademo = 'vehicles.svg#ev_plug_chademo',
    pantograph_bottom_up = 'vehicles.svg#pantograph_bottom_up',
    pantograph_top_down = 'vehicles.svg#pantograph_top_down',
    ev_plug_iec_61851_gbt = 'vehicles.svg#ev_plug_iec_61851_gbt',
}

export enum PlatformIcon {
    pxblue = 'platform.svg#pxblue',
    pxblue_small = 'platform.svg#pxblue_small',
    pxblue_small_alt = 'platform.svg#pxblue_small_alt',
    studioblue = 'platform.svg#studioblue',
    studioblue_outline = 'platform.svg#studioblue_outline',
    pxred = 'platform.svg#pxred',
    pxgreen = 'platform.svg#pxgreen',
    pxwhite = 'platform.svg#pxwhite',
    cybersecurity = 'platform.svg#cybersecurity',
    cybersecurity_two_tone = 'platform.svg#cybersecurity_two_tone',
}

export enum TransportationIcon {
    road = 'transportation.svg#road',
    road_alt = 'transportation.svg#road_alt',
}

export enum CommunicationIcon {
    satellite_uplink = 'communication.svg#satellite_uplink',
    traffic_light = 'communication.svg#traffic_light',
}

export enum PPEIcon {
    sign_caution = 'ppe.svg#sign_caution',
    ppe_level_two_tone = 'ppe.svg#ppe_level_two_tone',
    blast = 'ppe.svg#blast',
    arc_rated_hood = 'ppe.svg#arc_rated_hood',
    balaclava = 'ppe.svg#balaclava',
    overalls = 'ppe.svg#overalls',
    arc_rated_suit = 'ppe.svg#arc_rated_suit',
    glove = 'ppe.svg#glove',
    glove_alt = 'ppe.svg#glove_alt',
    insulated_glove = 'ppe.svg#insulated_glove',
    insulated_glove_alt = 'ppe.svg#insulated_glove_alt',
    double_triangle = 'ppe.svg#double_triangle',
    hard_hat = 'ppe.svg#hard_hat',
}

export enum StatusIcon {
    departments = 'status.svg#departments',
    department = 'status.svg#department',
    piggy_bank = 'status.svg#piggy_bank',
    map_marker_multiple = 'status.svg#map_marker_multiple',
    map_marker_three = 'status.svg#map_marker_three',
    outline_offline_bolt = 'status.svg#outline_offline_bolt',
    voltage_ac = 'status.svg#voltage_ac',
    voltage_dc = 'status.svg#voltage_dc',
    current_ac = 'status.svg#current_ac',
    current_dc = 'status.svg#current_dc',
    ac = 'status.svg#ac',
    dc = 'status.svg#dc',
    power_ac = 'status.svg#power_ac',
    power_dc = 'status.svg#power_dc',
    power_apparent_ac = 'status.svg#power_apparent_ac',
    line_to_line = 'status.svg#line_to_line',
    line_to_neutral = 'status.svg#line_to_neutral',
    device_activating = 'status.svg#device_activating',
    distance_apart = 'status.svg#distance_apart',
    ppe_level = 'status.svg#ppe_level',
}

export enum IndustrialIcon {
    factory = 'industrial.svg#factory',
}

export enum DeviceIcon {
    ami_gateway = 'device.svg#ami_gateway',
}

export enum PpeIcon {
    ippe_vibrate = 'ppe.svg#ippe_vibrate',
    ippe_vibrate_outlined = 'ppe.svg#ippe_vibrate_outlined',
    ippe_vibrate_off = 'ppe.svg#ippe_vibrate_off',
    safety_boot = 'ppe.svg#safety_boot',
    safety_glasses = 'ppe.svg#safety_glasses',
    hearing_protection = 'ppe.svg#hearing_protection',
    glasses = 'ppe.svg#glasses',
    glass_divider = 'ppe.svg#glass_divider',
    ppe_level = 'ppe.svg#ppe_level',
}

export enum PlatformsIcon {
    eaton = 'platforms.svg#eaton',
    eaton_tagline = 'platforms.svg#eaton_tagline',
    eaton_two_tone = 'platforms.svg#eaton_two_tone',
}

export enum GeneralIcon {
    account_settings = 'general.svg#account_settings',
    lock_reset = 'general.svg#lock_reset',
    technician = 'general.svg#technician',
    configuration = 'general.svg#configuration',
    device_configuration = 'general.svg#device_configuration',
    control = 'general.svg#control',
    diagnostic_alt = 'general.svg#diagnostic_alt',
    diagnostic = 'general.svg#diagnostic',
    api = 'general.svg#api',
    api_settings = 'general.svg#api_settings',
    paywall = 'general.svg#paywall',
    protocol = 'general.svg#protocol',
    notifications_active_outline = 'general.svg#notifications_active_outline',
}

export enum GeneralIcon {
    internet = 'general.svg#internet',
}

export enum SystemIcon {
    face_id = 'system.svg#face_id',
    file_pdf = 'system.svg#file_pdf',
    file_doc = 'system.svg#file_doc',
    database = 'system.svg#database',
    file_csv = 'system.svg#file_csv',
}

export enum CompaniesIcon {
    apple_logo = 'companies.svg#apple_logo',
    google = 'companies.svg#google',
    amazon = 'companies.svg#amazon',
    amazon_alexa = 'companies.svg#amazon_alexa',
    hubject = 'companies.svg#hubject',
}

export enum DevicesIcon {
    device_with_keypad = 'devices.svg#device_with_keypad',
    outlet_c19 = 'devices.svg#outlet_c19',
    outlet_c14 = 'devices.svg#outlet_c14',
    outlet_c39 = 'devices.svg#outlet_c39',
    outlet_alt = 'devices.svg#outlet_alt',
    outlet_c19_off = 'devices.svg#outlet_c19_off',
    outlet_c14_off = 'devices.svg#outlet_c14_off',
    outlet_c39_off = 'devices.svg#outlet_c39_off',
    outlet_alt_off = 'devices.svg#outlet_alt_off',
    champ_vmvl = 'devices.svg#champ_vmvl',
}

export enum ToolsIcon {
    pliers = 'tools.svg#pliers',
    screwdriver = 'tools.svg#screwdriver',
    box_cutter = 'tools.svg#box_cutter',
    hammer = 'tools.svg#hammer',
    home_repair_service_outline = 'tools.svg#home_repair_service_outline',
    tv_remote = 'tools.svg#tv_remote',
}

export enum CompaniesIcon {
    angular = 'companies.svg#angular',
    react = 'companies.svg#react',
    github = 'companies.svg#github',
}

export enum ToolsIcon {
    multimeter = 'tools.svg#multimeter',
    multimeter_outline = 'tools.svg#multimeter_outline',
    screw_head_slotted = 'tools.svg#screw_head_slotted',
    screw_head_phillips = 'tools.svg#screw_head_phillips',
    heat_shrink_tube = 'tools.svg#heat_shrink_tube',
}

export enum ResidentialIcon {
    skillet = 'residential.svg#skillet',
    skillet_cooktop = 'residential.svg#skillet_cooktop',
    cooking = 'residential.svg#cooking',
    stockpot = 'residential.svg#stockpot',
    stove = 'residential.svg#stove',
    iot_scene = 'residential.svg#iot_scene',
}

export enum WeatherIcon {
    theme_light_dark = 'weather.svg#theme_light_dark',
}

export type BluiIcon = DevicesIcon | DeviceIcon | SportsIcon | LightingIcon | StatusIcon | ToggleIcon | IndustrialIcon | AgricultureIcon | MapsIcon | VehiclesIcon | PlatformIcon | TransportationIcon | CommunicationIcon | PPEIcon | StatusIcon | IndustrialIcon | DeviceIcon | PpeIcon | PlatformsIcon | GeneralIcon | GeneralIcon | SystemIcon | CompaniesIcon | DevicesIcon | ToolsIcon | CompaniesIcon | ToolsIcon | ResidentialIcon | WeatherIcon;
