name: CI Run

on:
  push:
    branches: [ "dev", "master" ]
  pull_request:
    branches: [ "dev", "master" ]
  pull_request_target:
    types:
      - opened
    branches:
      - '*/*'

permissions:
  pull-requests: write
  contents: read

jobs:
  prettier_lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - run: yarn install --immutable
    - run: yarn prettier:check
    - run: yarn lint

  build_icons_library:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - run: yarn install --immutable
    - run: yarn build
    - name: Zip artifacts
      run: zip node_modules.zip ./* -r
    - name: Save node modules
      uses: actions/upload-artifact@v3
      with:
        name: node_modules
        if-no-files-found: error
        path: node_modules.zip
    - name: Save .yarn file
      uses: actions/upload-artifact@v3
      with:
        name: .yarn
        if-no-files-found: error
        path: .yarn
    - name: Save yarnrc file
      uses: actions/upload-artifact@v3
      with:
        name: yarnrc.yml
        if-no-files-found: error
        path: yarnrc.yml
    - name: Save build icon packages
      uses: actions/upload-artifact@v3
      with:
        if-no-files-found: error
        path: packages/*

  # test_artifacts:
  #   runs-on: ubuntu-latest
  #   needs: build_icons_library
  #   steps:
  #   - name: Checkout
  #     uses: actions/checkout@v4
  #   - name: Download the icon-font folder
  #     uses: actions/download-artifact@v3
  #     with:
  #       name: icon-font
  #       path: packages/icon-font
  #   - name: Download the svg folder
  #     uses: actions/download-artifact@v3
  #     with:
  #       name: svg
  #       path: packages/svg
  #   - name: Download the rn-vector folder
  #     uses: actions/download-artifact@v3
  #     with:
  #       name: rn-vector
  #       path: packages/rn-vector
  #   - name: Download the mui folder
  #     uses: actions/download-artifact@v3
  #     with:
  #       name: mui
  #       path: packages/mui
  #   - run: yarn test

  # build_demo:
  #   runs-on: ubuntu-latest

  #   strategy:
  #     matrix:
  #       node-version: [18.x]

  #   steps:
  #   - name: Checkout
  #     uses: actions/checkout@v4
  #   - name: Use Node.js ${{ matrix.node-version }}
  #     uses: actions/setup-node@v4
  #     with:
  #       node-version: ${{ matrix.node-version }}
  #       cache: 'yarn'
  #   - run: yarn --frozen-lockfile
  #     working-directory: demos/react-demo
  #   - run: yarn build
  #     working-directory: demos/react-demo

  # publish:
  #   runs-on: ubuntu-latest
  #   if: ${{ github.event_name == 'push' && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev') }}
  #   needs: build_icons_library
  #   strategy:
  #     matrix:
  #       node-version: [18.x]
  #   env:
  #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  #     BRANCH: ${{ github.ref == 'refs/heads/master' && 'master' || 'dev' }}
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Download icon font package
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: iconfont
  #         path: packages/iconfont
  #     - name: Download svg package
  #       uses: actions/download-artifact@v3
  #       with:
  #           name: svg
  #           path: packages/svg
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: ${{ matrix.node-version }}
  #         registry-url: 'https://registry.npmjs.org'
  #     - run: yarn --frozen-lockfile
  #     - run: yarn publish:package -b ${{env.BRANCH}}